# Site settings
title: Tidy Data by Kwg
email: kevingilds@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Discuss nonprofit evaluation, R, and Python. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  kgilds

# Build settings
markdown: kramdown
